### ISSUE TITLE
Change the name

### ISSUE THREAD

**Issue by endolith** [FelixLoether/flask-image-upload-thing#4]
Wait, so this [Flask-Uploads](http://flask-uploads.readthedocs.org/en/latest/) is not the same as the [Flask-Uploads](https://pythonhosted.org/Flask-Uploads/) that is [linked from the Flask docs](http://flask.pocoo.org/docs/dev/patterns/fileuploads/)?  So that's why the functionality is different when I try to learn it from different pages?  So this one is `flask.ext.uploads` and that one is `flaskext.uploads`??  This is very confusing.   [So this is not a "change in path" from one version to the next?](http://stackoverflow.com/q/24968242/125507)

If this came second, please change this one to a distinct name and package name.

**Comment by jeffwidman** [comment]
@FelixLoether if it's not too much of a bother, would you mind changing the name to something more distinctive? 

I just took over as the [new maintainer of the original Flask-Uploads project](https://github.com/mitsuhiko/flask/pull/1493#issuecomment-164599182). I was going through old questions on StackOverflow to see if there were any outstanding issues that weren't already mentioned in the issuetracker, and it was confusing because a couple of questions mentioned this library instead of the other one.

**Comment by FelixLoether** [comment]
:+1:

**Comment by jeffwidman** [comment]
Thanks, much appreciated!
